/**
 * DADOS MOCKADOS PARA MÓDULO COLABORADOR
 * Sistema ERP Minerva Engenharia
 * 
 * Este arquivo centraliza todos os dados de exemplo para os 7 módulos do fluxo colaborador
 */

// === USUÁRIO LOGADO ===
export const mockUserColaborador = {
  id: 1,
  nome: "Carlos Silva",
  email: "carlos.silva@minervaengenharia.com.br",
  role_nivel: 4, // Colaborador
  setor: "ADMINISTRATIVO", // ou "OPERACIONAL"
  telefone: "(11) 98765-4321",
  criadoEm: "2024-01-15",
};

// === ORDENS DE SERVIÇO ===
export const mockOrdensServico = [
  // OS com prazo vencido - ALTA prioridade
  {
    id: 1,
    codigo: "OS-007-2025",
    tipo: "OS_07",
    cliente: "Construtora ABC Ltda",
    endereco: "Av. Paulista, 1000 - São Paulo/SP",
    cep: "01310-100",
    telefone: "(11) 98765-4321",
    email: "contato@construtorabc.com.br",
    etapaAtual: "VISTORIA",
    status: "atrasado",
    prioridade: "ALTA",
    prazo: "2025-11-15",
    responsavel: "Carlos Silva",
    descricao: "Vistoria técnica para análise estrutural do edifício comercial com 8 andares",
    criadoEm: "2025-11-10",
  },
  {
    id: 2,
    codigo: "OS-013-2025",
    tipo: "OS_13",
    cliente: "Empresa XYZ S.A.",
    endereco: "Rua das Flores, 500 - Rio de Janeiro/RJ",
    cep: "20000-000",
    telefone: "(21) 91234-5678",
    email: "obras@empresaxyz.com.br",
    etapaAtual: "EXECUCAO",
    status: "em_andamento",
    prioridade: "ALTA",
    prazo: "2025-11-18",
    responsavel: "Carlos Silva",
    descricao: "Execução de projeto elétrico industrial - Complexo fabril 5.000m²",
    criadoEm: "2025-11-12",
  },
  {
    id: 3,
    codigo: "OS-005-2025",
    tipo: "OS_05",
    cliente: "Indústria 123 Ltda",
    endereco: "Rod. dos Bandeirantes, Km 20 - Campinas/SP",
    cep: "13050-000",
    telefone: "( 19) 99999-8888",
    email: "industria123@email.com",
    etapaAtual: "FOLLOW_UP_1",
    status: "atrasado",
    prioridade: "ALTA",
    prazo: "2025-11-14",
    responsavel: "Carlos Silva",
    descricao: "Regularização de AVCB - Primeiro acompanhamento com cliente",
    criadoEm: "2025-11-08",
  },
  {
    id: 4,
    codigo: "OS-010-2025",
    tipo: "OS_10",
    cliente: "Comércio ZZZ Eireli",
    endereco: "Av. Brasil, 2000 - Brasília/DF",
    cep: "70000-000",
    telefone: "(61) 98888-7777",
    email: "contato@comerciozzz.com.br",
    etapaAtual: "ANALISE_TECNICA",
    status: "em_andamento",
    prioridade: "MEDIA",
    prazo: "2025-11-19",
    responsavel: "Carlos Silva",
    descricao: "Análise técnica para adequação de instalações elétricas",
    criadoEm: "2025-11-14",
  },
  {
    id: 5,
    codigo: "OS-008-2025",
    tipo: "OS_08",
    cliente: "Residencial Park Ltda",
    endereco: "Rua das Acácias, 100 - Belo Horizonte/MG",
    cep: "30000-000",
    telefone: "(31) 97777-6666",
    email: "residencialpark@email.com",
    etapaAtual: "VISTORIA",
    status: "em_andamento",
    prioridade: "MEDIA",
    prazo: "2025-11-22",
    responsavel: "Carlos Silva",
    descricao: "Vistoria técnica em condomínio residencial - 120 unidades",
    criadoEm: "2025-11-16",
  },
  {
    id: 6,
    codigo: "OS-001-2025",
    tipo: "OS_01",
    cliente: "Shopping Center Norte",
    endereco: "Av. Marginal Tietê, 3500 - São Paulo/SP",
    cep: "02071-000",
    telefone: "(11) 94444-3333",
    email: "obras@shoppingnorte.com.br",
    etapaAtual: "GERAR_PROPOSTA",
    status: "em_andamento",
    prioridade: "ALTA",
    prazo: "2025-11-20",
    responsavel: "Carlos Silva",
    descricao: "Elaboração de proposta para PPCI - Shopping 45.000m²",
    criadoEm: "2025-11-13",
  },
  {
    id: 7,
    codigo: "OS-003-2025",
    tipo: "OS_03",
    cliente: "Hospital São Lucas",
    endereco: "Rua Dr. Silva, 800 - Porto Alegre/RS",
    cep: "90000-000",
    telefone: "(51) 93333-2222",
    email: "engenharia@hospitalsaolucas.com.br",
    etapaAtual: "MEMORIAL_ESCOPO",
    status: "em_andamento",
    prioridade: "ALTA",
    prazo: "2025-11-21",
    responsavel: "Carlos Silva",
    descricao: "Memorial descritivo para adequação de sistemas de segurança",
    criadoEm: "2025-11-15",
  },
  {
    id: 8,
    codigo: "OS-009-2025",
    tipo: "OS_09",
    cliente: "Universidade Federal do ABC",
    endereco: "Av. dos Estados, 5001 - Santo André/SP",
    cep: "09210-580",
    telefone: "(11) 92222-1111",
    email: "infraestrutura@ufabc.edu.br",
    etapaAtual: "REQUISICAO_COMPRA",
    status: "pendente",
    prioridade: "BAIXA",
    prazo: "2025-11-25",
    responsavel: "Carlos Silva",
    descricao: "Requisição de materiais para obra civil no campus",
    criadoEm: "2025-11-17",
  },
  {
    id: 9,
    codigo: "OS-002-2025",
    tipo: "OS_02",
    cliente: "Indústria Farmacêutica Global",
    endereco: "Rod. Anhanguera, Km 105 - Campinas/SP",
    cep: "13069-901",
    telefone: "(19) 98888-9999",
    email: "facilities@farmaglobal.com.br",
    etapaAtual: "FOLLOWUP_2",
    status: "em_andamento",
    prioridade: "MEDIA",
    prazo: "2025-11-23",
    responsavel: "Carlos Silva",
    descricao: "Segundo follow-up de projeto de AVCB industrial",
    criadoEm: "2025-11-11",
  },
  {
    id: 10,
    codigo: "OS-006-2025",
    tipo: "OS_06",
    cliente: "Condomínio Empresarial Ipiranga",
    endereco: "Av. Ipiranga, 2500 - São Paulo/SP",
    cep: "01046-000",
    telefone: "(11) 91111-0000",
    email: "sindico@condipiranga.com.br",
    etapaAtual: "REALIZACAO_APRESENTACAO",
    status: "em_andamento",
    prioridade: "MEDIA",
    prazo: "2025-11-24",
    responsavel: "Carlos Silva",
    descricao: "Apresentação de projeto de prevenção contra incêndio",
    criadoEm: "2025-11-16",
  },
  {
    id: 11,
    codigo: "OS-004-2025",
    tipo: "OS_04",
    cliente: "Hotel Minerva Palace",
    endereco: "Rua Augusta, 1500 - São Paulo/SP",
    cep: "01304-001",
    telefone: "(11) 90000-8888",
    email: "gerencia@hotelminverva.com.br",
    etapaAtual: "CONTRATO_ASSINADO",
    status: "em_andamento",
    prioridade: "ALTA",
    prazo: "2025-11-26",
    responsavel: "Carlos Silva",
    descricao: "Processamento pós-assinatura de contrato para SPDA",
    criadoEm: "2025-11-12",
  },
  {
    id: 12,
    codigo: "OS-011-2025",
    tipo: "OS_11",
    cliente: "Supermercado Economia",
    endereco: "Av. Celso Garcia, 3000 - São Paulo/SP",
    cep: "03064-000",
    telefone: "(11) 98765-5555",
    email: "obras@supereconomia.com.br",
    etapaAtual: "EXECUCAO",
    status: "em_andamento",
    prioridade: "BAIXA",
    prazo: "2025-11-27",
    responsavel: "Carlos Silva",
    descricao: "Execução de projeto elétrico comercial - 1.200m²",
    criadoEm: "2025-11-14",
  },
  {
    id: 13,
    codigo: "OS-012-2025",
    tipo: "OS_12",
    cliente: "Clínica Odontológica Sorriso",
    endereco: "Rua Vergueiro, 1200 - São Paulo/SP",
    cep: "01504-001",
    telefone: "(11) 97777-4444",
    email: "clinica@sorriso.com.br",
    etapaAtual: "DOCUMENTACAO_SST",
    status: "pendente",
    prioridade: "MEDIA",
    prazo: "2025-11-28",
    responsavel: "Carlos Silva",
    descricao: "Documentação de Saúde e Segurança do Trabalho",
    criadoEm: "2025-11-15",
  },
  {
    id: 14,
    codigo: "OS-007-2024",
    tipo: "OS_07",
    cliente: "Academia Fitness Pro",
    endereco: "Av. Rebouças, 2100 - São Paulo/SP",
    cep: "05402-100",
    telefone: "(11) 96666-3333",
    email: "adm@fitnesspro.com.br",
    etapaAtual: "ANALISE_TECNICA",
    status: "em_andamento",
    prioridade: "BAIXA",
    prazo: "2025-11-29",
    responsavel: "Carlos Silva",
    descricao: "Análise para regularização de instalações esportivas",
    criadoEm: "2025-11-13",
  },
  {
    id: 15,
    codigo: "OS-008-2024",
    tipo: "OS_08",
    cliente: "Escritório de Advocacia Pinheiro & Associados",
    endereco: "Av. Brigadeiro Faria Lima, 2000 - São Paulo/SP",
    cep: "01451-000",
    telefone: "(11) 95555-2222",
    email: "administrativo@pinheiroassociados.com.br",
    etapaAtual: "VISTORIA",
    status: "pendente",
    prioridade: "BAIXA",
    prazo: "2025-11-30",
    responsavel: "Carlos Silva",
    descricao: "Vistoria de segurança em escritório corporativo",
    criadoEm: "2025-11-17",
  },
  {
    id: 16,
    codigo: "OS-013-2024",
    tipo: "OS_13",
    cliente: "Restaurante Gourmet Brasil",
    endereco: "Rua Oscar Freire, 500 - São Paulo/SP",
    cep: "01426-001",
    telefone: "(11) 94444-1111",
    email: "proprietario@gourmetbrasil.com.br",
    etapaAtual: "CRONOGRAMA_OBRA",
    status: "em_andamento",
    prioridade: "MEDIA",
    prazo: "2025-12-01",
    responsavel: "Carlos Silva",
    descricao: "Elaboração de cronograma para reforma completa",
    criadoEm: "2025-11-16",
  },
  {
    id: 17,
    codigo: "OS-005-2024",
    tipo: "OS_05",
    cliente: "Colégio São Francisco",
    endereco: "Rua dos Pinheiros, 800 - São Paulo/SP",
    cep: "05422-001",
    telefone: "(11) 93333-0000",
    email: "diretoria@colegiosaofrancisco.edu.br",
    etapaAtual: "FOLLOW_UP_3",
    status: "em_andamento",
    prioridade: "ALTA",
    prazo: "2025-12-02",
    responsavel: "Carlos Silva",
    descricao: "Terceiro acompanhamento - Adequação de saídas de emergência",
    criadoEm: "2025-11-09",
  },
  {
    id: 18,
    codigo: "OS-010-2024",
    tipo: "OS_10",
    cliente: "Laboratório de Análises Clínicas LabVida",
    endereco: "Av. Angélica, 1500 - São Paulo/SP",
    cep: "01227-200",
    telefone: "(11) 92222-9999",
    email: "administrativo@labvida.com.br",
    etapaAtual: "ANALISE_TECNICA",
    status: "atrasado",
    prioridade: "ALTA",
    prazo: "2025-11-16",
    responsavel: "Carlos Silva",
    descricao: "Análise técnica urgente para renovação de licença sanitária",
    criadoEm: "2025-11-07",
  },
];

// === CLIENTES ===
export const mockClientes = [
  {
    id: 1,
    nome: "Construtora ABC Ltda",
    cnpj: "12.345.678/0001-90",
    endereco: "Av. Paulista, 1000 - São Paulo/SP",
    cep: "01310-100",
    telefone: "(11) 98765-4321",
    email: "contato@construtorabc.com.br",
    tipo: "PESSOA_JURIDICA",
    status: "ATIVO",
  },
  {
    id: 2,
    nome: "Empresa XYZ S.A.",
    cnpj: "98.765.432/0001-10",
    endereco: "Rua das Flores, 500 - Rio de Janeiro/RJ",
    cep: "20000-000",
    telefone: "(21) 91234-5678",
    email: "comercial@empresaxyz.com.br",
    tipo: "PESSOA_JURIDICA",
    status: "ATIVO",
  },
  {
    id: 3,
    nome: "Indústria 123 Ltda",
    cnpj: "11.222.333/0001-44",
    endereco: "Rod. dos Bandeirantes, Km 20 - Campinas/SP",
    cep: "13050-000",
    telefone: "(19) 99999-8888",
    email: "industria123@email.com",
    tipo: "PESSOA_JURIDICA",
    status: "ATIVO",
  },
  {
    id: 4,
    nome: "Comércio ZZZ Eireli",
    cnpj: "44.555.666/0001-77",
    endereco: "Av. Brasil, 2000 - Brasília/DF",
    cep: "70000-000",
    telefone: "(61) 98888-7777",
    email: "contato@comerciozzz.com.br",
    tipo: "PESSOA_JURIDICA",
    status: "ATIVO",
  },
  {
    id: 5,
    nome: "Residencial Park Ltda",
    cnpj: "77.888.999/0001-00",
    endereco: "Rua das Acácias, 100 - Belo Horizonte/MG",
    cep: "30000-000",
    telefone: "(31) 97777-6666",
    email: "residencialpark@email.com",
    tipo: "PESSOA_JURIDICA",
    status: "ATIVO",
  },
  {
    id: 6,
    nome: "João da Silva",
    cpf: "123.456.789-00",
    endereco: "Rua das Palmeiras, 250 - Santos/SP",
    cep: "11000-000",
    telefone: "(13) 96666-5555",
    email: "joao.silva@email.com",
    tipo: "PESSOA_FISICA",
    status: "ATIVO",
  },
  {
    id: 7,
    nome: "Shopping Center Norte",
    cnpj: "22.333.444/0001-55",
    endereco: "Av. Marginal Tietê, 3500 - São Paulo/SP",
    cep: "02071-000",
    telefone: "(11) 94444-3333",
    email: "obras@shoppingnorte.com.br",
    tipo: "PESSOA_JURIDICA",
    status: "ATIVO",
  },
  {
    id: 8,
    nome: "Hospital São Lucas",
    cnpj: "33.444.555/0001-66",
    endereco: "Rua Dr. Silva, 800 - Porto Alegre/RS",
    cep: "90000-000",
    telefone: "(51) 93333-2222",
    email: "engenharia@hospitalsaolucas.com.br",
    tipo: "PESSOA_JURIDICA",
    status: "ATIVO",
  },
  {
    id: 9,
    nome: "Universidade Federal do ABC",
    cnpj: "44.555.666/0001-77",
    endereco: "Av. dos Estados, 5001 - Santo André/SP",
    cep: "09210-580",
    telefone: "(11) 92222-1111",
    email: "infraestrutura@ufabc.edu.br",
    tipo: "PESSOA_JURIDICA",
    status: "ATIVO",
  },
  {
    id: 10,
    nome: "Indústria Farmacêutica Global",
    cnpj: "55.666.777/0001-88",
    endereco: "Rod. Anhanguera, Km 105 - Campinas/SP",
    cep: "13069-901",
    telefone: "(19) 98888-9999",
    email: "facilities@farmaglobal.com.br",
    tipo: "PESSOA_JURIDICA",
    status: "ATIVO",
  },
  {
    id: 11,
    nome: "Maria Santos Oliveira",
    cpf: "987.654.321-00",
    endereco: "Av. Atlântica, 1200 - Rio de Janeiro/RJ",
    cep: "22021-000",
    telefone: "(21) 99999-8888",
    email: "maria.santos@email.com",
    tipo: "PESSOA_FISICA",
    status: "ATIVO",
  },
  {
    id: 12,
    nome: "Condomínio Empresarial Ipiranga",
    cnpj: "66.777.888/0001-99",
    endereco: "Av. Ipiranga, 2500 - São Paulo/SP",
    cep: "01046-000",
    telefone: "(11) 91111-0000",
    email: "sindico@condipiranga.com.br",
    tipo: "PESSOA_JURIDICA",
    status: "ATIVO",
  },
  {
    id: 13,
    nome: "Hotel Minerva Palace",
    cnpj: "77.888.999/0001-11",
    endereco: "Rua Augusta, 1500 - São Paulo/SP",
    cep: "01304-001",
    telefone: "(11) 90000-8888",
    email: "gerencia@hotelminverva.com.br",
    tipo: "PESSOA_JURIDICA",
    status: "ATIVO",
  },
  {
    id: 14,
    nome: "Supermercado Economia",
    cnpj: "88.999.000/0001-22",
    endereco: "Av. Celso Garcia, 3000 - São Paulo/SP",
    cep: "03064-000",
    telefone: "(11) 98765-5555",
    email: "obras@supereconomia.com.br",
    tipo: "PESSOA_JURIDICA",
    status: "ATIVO",
  },
  {
    id: 15,
    nome: "Pedro Henrique Costa",
    cpf: "456.789.123-00",
    endereco: "Rua XV de Novembro, 300 - Curitiba/PR",
    cep: "80020-310",
    telefone: "(41) 98888-7777",
    email: "pedro.costa@email.com",
    tipo: "PESSOA_FISICA",
    status: "ATIVO",
  },
  {
    id: 16,
    nome: "Clínica Odontológica Sorriso",
    cnpj: "99.000.111/0001-33",
    endereco: "Rua Vergueiro, 1200 - São Paulo/SP",
    cep: "01504-001",
    telefone: "(11) 97777-4444",
    email: "clinica@sorriso.com.br",
    tipo: "PESSOA_JURIDICA",
    status: "ATIVO",
  },
  {
    id: 17,
    nome: "Academia Fitness Pro",
    cnpj: "00.111.222/0001-44",
    endereco: "Av. Rebouças, 2100 - São Paulo/SP",
    cep: "05402-100",
    telefone: "(11) 96666-3333",
    email: "adm@fitnesspro.com.br",
    tipo: "PESSOA_JURIDICA",
    status: "ATIVO",
  },
  {
    id: 18,
    nome: "Ana Paula Ferreira",
    cpf: "789.123.456-00",
    endereco: "Av. Boa Viagem, 5000 - Recife/PE",
    cep: "51021-000",
    telefone: "(81) 99999-6666",
    email: "ana.ferreira@email.com",
    tipo: "PESSOA_FISICA",
    status: "ATIVO",
  },
  {
    id: 19,
    nome: "Escritório de Advocacia Pinheiro & Associados",
    cnpj: "11.222.333/0001-55",
    endereco: "Av. Brigadeiro Faria Lima, 2000 - São Paulo/SP",
    cep: "01451-000",
    telefone: "(11) 95555-2222",
    email: "administrativo@pinheiroassociados.com.br",
    tipo: "PESSOA_JURIDICA",
    status: "ATIVO",
  },
  {
    id: 20,
    nome: "Restaurante Gourmet Brasil",
    cnpj: "22.333.444/0001-66",
    endereco: "Rua Oscar Freire, 500 - São Paulo/SP",
    cep: "01426-001",
    telefone: "(11) 94444-1111",
    email: "proprietario@gourmetbrasil.com.br",
    tipo: "PESSOA_JURIDICA",
    status: "ATIVO",
  },
  {
    id: 21,
    nome: "Roberto Lima Santos",
    cpf: "321.654.987-00",
    endereco: "Av. Sete de Setembro, 1500 - Salvador/BA",
    cep: "40060-001",
    telefone: "(71) 98888-5555",
    email: "roberto.lima@email.com",
    tipo: "PESSOA_FISICA",
    status: "ATIVO",
  },
  {
    id: 22,
    nome: "Colégio São Francisco",
    cnpj: "33.444.555/0001-77",
    endereco: "Rua dos Pinheiros, 800 - São Paulo/SP",
    cep: "05422-001",
    telefone: "(11) 93333-0000",
    email: "diretoria@colegiosaofrancisco.edu.br",
    tipo: "PESSOA_JURIDICA",
    status: "ATIVO",
  },
  {
    id: 23,
    nome: "Laboratório de Análises Clínicas LabVida",
    cnpj: "44.555.666/0001-88",
    endereco: "Av. Angélica, 1500 - São Paulo/SP",
    cep: "01227-200",
    telefone: "(11) 92222-9999",
    email: "administrativo@labvida.com.br",
    tipo: "PESSOA_JURIDICA",
    status: "ATIVO",
  },
  {
    id: 24,
    nome: "Fernanda Souza Almeida",
    cpf: "654.987.321-00",
    endereco: "Rua das Acácias, 250 - Fortaleza/CE",
    cep: "60115-000",
    telefone: "(85) 99999-4444",
    email: "fernanda.souza@email.com",
    tipo: "PESSOA_FISICA",
    status: "ATIVO",
  },
  {
    id: 25,
    nome: "Padaria e Confeitaria Pão Dourado",
    cnpj: "55.666.777/0001-99",
    endereco: "Rua da Consolação, 2500 - São Paulo/SP",
    cep: "01416-001",
    telefone: "(11) 91111-8888",
    email: "contato@paodourado.com.br",
    tipo: "PESSOA_JURIDICA",
    status: "ATIVO",
  },
  {
    id: 26,
    nome: "Carlos Eduardo Rocha",
    cpf: "159.753.486-00",
    endereco: "Av. Afonso Pena, 3500 - Belo Horizonte/MG",
    cep: "30130-009",
    telefone: "(31) 98888-3333",
    email: "carlos.rocha@email.com",
    tipo: "PESSOA_FISICA",
    status: "ATIVO",
  },
  {
    id: 27,
    nome: "Posto de Combustível Estrela",
    cnpj: "66.777.888/0001-00",
    endereco: "Av. dos Bandeirantes, 1200 - Ribeirão Preto/SP",
    cep: "14025-670",
    telefone: "(16) 99999-2222",
    email: "gerencia@postoestrela.com.br",
    tipo: "PESSOA_JURIDICA",
    status: "ATIVO",
  },
  {
    id: 28,
    nome: "Juliana Martins Pereira",
    cpf: "753.951.852-00",
    endereco: "Rua Barão do Rio Branco, 800 - Florianópolis/SC",
    cep: "88015-200",
    telefone: "(48) 98888-1111",
    email: "juliana.martins@email.com",
    tipo: "PESSOA_FISICA",
    status: "ATIVO",
  },
  {
    id: 29,
    nome: "Farmácia Popular Saúde",
    cnpj: "77.888.999/0001-11",
    endereco: "Rua do Comércio, 600 - Sorocaba/SP",
    cep: "18010-140",
    telefone: "(15) 99999-0000",
    email: "farmacia@popularsaude.com.br",
    tipo: "PESSOA_JURIDICA",
    status: "ATIVO",
  },
  {
    id: 30,
    nome: "Ricardo Alves Mendes",
    cpf: "852.741.963-00",
    endereco: "Av. Goiás, 1500 - Goiânia/GO",
    cep: "74063-010",
    telefone: "(62) 98888-9999",
    email: "ricardo.mendes@email.com",
    tipo: "PESSOA_FISICA",
    status: "ATIVO",
  },
];

// === EVENTOS DA AGENDA ===
export const mockEventosAgenda = [
  {
    id: 1,
    titulo: "Vistoria - Construtora ABC",
    osId: 1,
    osCodigo: "OS-007-2025",
    cliente: "Construtora ABC Ltda",
    endereco: "Av. Paulista, 1000 - São Paulo/SP",
    data: "2025-11-18",
    horaInicio: "09:00",
    horaFim: "11:00",
    tipo: "VISTORIA",
    responsavel: "Carlos Silva",
  },
  {
    id: 2,
    titulo: "Reunião com Cliente - Empresa XYZ",
    osId: 2,
    osCodigo: "OS-013-2025",
    cliente: "Empresa XYZ S.A.",
    endereco: "Rua das Flores, 500 - Rio de Janeiro/RJ",
    data: "2025-11-19",
    horaInicio: "14:00",
    horaFim: "16:00",
    tipo: "REUNIAO",
    responsavel: "Carlos Silva",
  },
  {
    id: 3,
    titulo: "Vistoria - Residencial Park",
    osId: 5,
    osCodigo: "OS-008-2025",
    cliente: "Residencial Park Ltda",
    endereco: "Rua das Acácias, 100 - Belo Horizonte/MG",
    data: "2025-11-22",
    horaInicio: "10:00",
    horaFim: "12:00",
    tipo: "VISTORIA",
    responsavel: "Carlos Silva",
  },
  {
    id: 4,
    titulo: "Follow-up - Indústria 123",
    osId: 3,
    osCodigo: "OS-005-2025",
    cliente: "Indústria 123 Ltda",
    endereco: "Rod. dos Bandeirantes, Km 20 - Campinas/SP",
    data: "2025-11-20",
    horaInicio: "15:00",
    horaFim: "16:30",
    tipo: "FOLLOW_UP",
    responsavel: "Carlos Silva",
  },
  {
    id: 5,
    titulo: "Apresentação de Proposta - Shopping Norte",
    osId: 6,
    osCodigo: "OS-001-2025",
    cliente: "Shopping Center Norte",
    endereco: "Av. Marginal Tietê, 3500 - São Paulo/SP",
    data: "2025-11-21",
    horaInicio: "10:00",
    horaFim: "11:30",
    tipo: "APRESENTACAO",
    responsavel: "Carlos Silva",
  },
  {
    id: 6,
    titulo: "Análise Técnica - Hospital São Lucas",
    osId: 7,
    osCodigo: "OS-003-2025",
    cliente: "Hospital São Lucas",
    endereco: "Rua Dr. Silva, 800 - Porto Alegre/RS",
    data: "2025-11-23",
    horaInicio: "09:00",
    horaFim: "12:00",
    tipo: "ANALISE_TECNICA",
    responsavel: "Carlos Silva",
  },
  {
    id: 7,
    titulo: "Vistoria - Comércio ZZZ",
    osId: 4,
    osCodigo: "OS-010-2025",
    cliente: "Comércio ZZZ Eireli",
    endereco: "Av. Brasil, 2000 - Brasília/DF",
    data: "2025-11-25",
    horaInicio: "14:00",
    horaFim: "16:00",
    tipo: "VISTORIA",
    responsavel: "Carlos Silva",
  },
  {
    id: 8,
    titulo: "Reunião de Planejamento - UFABC",
    osId: 8,
    osCodigo: "OS-009-2025",
    cliente: "Universidade Federal do ABC",
    endereco: "Av. dos Estados, 5001 - Santo André/SP",
    data: "2025-11-26",
    horaInicio: "10:00",
    horaFim: "11:00",
    tipo: "REUNIAO",
    responsavel: "Carlos Silva",
  },
  {
    id: 9,
    titulo: "Follow-up - Farmacêutica Global",
    osId: 9,
    osCodigo: "OS-002-2025",
    cliente: "Indústria Farmacêutica Global",
    endereco: "Rod. Anhanguera, Km 105 - Campinas/SP",
    data: "2025-11-24",
    horaInicio: "15:00",
    horaFim: "17:00",
    tipo: "FOLLOW_UP",
    responsavel: "Carlos Silva",
  },
  {
    id: 10,
    titulo: "Apresentação Técnica - Condomínio Ipiranga",
    osId: 10,
    osCodigo: "OS-006-2025",
    cliente: "Condomínio Empresarial Ipiranga",
    endereco: "Av. Ipiranga, 2500 - São Paulo/SP",
    data: "2025-11-27",
    horaInicio: "19:00",
    horaFim: "20:30",
    tipo: "APRESENTACAO",
    responsavel: "Carlos Silva",
  },
  {
    id: 11,
    titulo: "Vistoria Final - Hotel Minerva",
    osId: 11,
    osCodigo: "OS-004-2025",
    cliente: "Hotel Minerva Palace",
    endereco: "Rua Augusta, 1500 - São Paulo/SP",
    data: "2025-11-28",
    horaInicio: "11:00",
    horaFim: "13:00",
    tipo: "VISTORIA",
    responsavel: "Carlos Silva",
  },
  {
    id: 12,
    titulo: "Inspeção de Obra - Supermercado Economia",
    osId: 12,
    osCodigo: "OS-011-2025",
    cliente: "Supermercado Economia",
    endereco: "Av. Celso Garcia, 3000 - São Paulo/SP",
    data: "2025-11-29",
    horaInicio: "08:00",
    horaFim: "10:00",
    tipo: "INSPECAO",
    responsavel: "Carlos Silva",
  },
  {
    id: 13,
    titulo: "Documentação SST - Clínica Sorriso",
    osId: 13,
    osCodigo: "OS-012-2025",
    cliente: "Clínica Odontológica Sorriso",
    endereco: "Rua Vergueiro, 1200 - São Paulo/SP",
    data: "2025-11-30",
    horaInicio: "14:00",
    horaFim: "15:30",
    tipo: "REUNIAO",
    responsavel: "Carlos Silva",
  },
  {
    id: 14,
    titulo: "Análise - Academia Fitness",
    osId: 14,
    osCodigo: "OS-007-2024",
    cliente: "Academia Fitness Pro",
    endereco: "Av. Rebouças, 2100 - São Paulo/SP",
    data: "2025-11-18",
    horaInicio: "16:00",
    horaFim: "17:00",
    tipo: "ANALISE_TECNICA",
    responsavel: "Carlos Silva",
  },
  {
    id: 15,
    titulo: "Vistoria Preventiva - Escritório Pinheiro",
    osId: 15,
    osCodigo: "OS-008-2024",
    cliente: "Escritório de Advocacia Pinheiro & Associados",
    endereco: "Av. Brigadeiro Faria Lima, 2000 - São Paulo/SP",
    data: "2025-12-01",
    horaInicio: "10:30",
    horaFim: "12:00",
    tipo: "VISTORIA",
    responsavel: "Carlos Silva",
  },
  {
    id: 16,
    titulo: "Reunião de Cronograma - Restaurante Gourmet",
    osId: 16,
    osCodigo: "OS-013-2024",
    cliente: "Restaurante Gourmet Brasil",
    endereco: "Rua Oscar Freire, 500 - São Paulo/SP",
    data: "2025-12-02",
    horaInicio: "09:00",
    horaFim: "10:30",
    tipo: "REUNIAO",
    responsavel: "Carlos Silva",
  },
  {
    id: 17,
    titulo: "Follow-up Urgente - Colégio São Francisco",
    osId: 17,
    osCodigo: "OS-005-2024",
    cliente: "Colégio São Francisco",
    endereco: "Rua dos Pinheiros, 800 - São Paulo/SP",
    data: "2025-11-19",
    horaInicio: "08:00",
    horaFim: "09:00",
    tipo: "FOLLOW_UP",
    responsavel: "Carlos Silva",
  },
  {
    id: 18,
    titulo: "Análise Urgente - LabVida",
    osId: 18,
    osCodigo: "OS-010-2024",
    cliente: "Laboratório de Análises Clínicas LabVida",
    endereco: "Av. Angélica, 1500 - São Paulo/SP",
    data: "2025-11-17",
    horaInicio: "13:00",
    horaFim: "15:00",
    tipo: "ANALISE_TECNICA",
    responsavel: "Carlos Silva",
  },
];

// === LEADS COMERCIAIS ===
export const mockLeads = [
  {
    id: 1,
    nome: "Empresa Potencial ABC Incorporadora",
    contato: "João Pedro Almeida",
    telefone: "(11) 99999-8888",
    email: "joao@empresaabc.com.br",
    origem: "INDICACAO",
    status: "NOVO",
    potencial: "ALTO",
    observacoes: "Interessado em serviços de assessoria para 3 empreendimentos",
    criadoPor: "Carlos Silva",
    criadoEm: "2025-11-15",
  },
  {
    id: 2,
    nome: "Construtora Nova Era Ltda",
    contato: "Maria Santos",
    telefone: "(21) 98888-7777",
    email: "maria@novaera.com.br",
    origem: "SITE",
    status: "EM_CONTATO",
    potencial: "MEDIO",
    observacoes: "Solicitou orçamento para vistoria de 2 obras em andamento",
    criadoPor: "Carlos Silva",
    criadoEm: "2025-11-12",
  },
  {
    id: 3,
    nome: "Indústria Tech Solutions Brasil",
    contato: "Roberto Lima Santos",
    telefone: "(11) 97777-6666",
    email: "roberto@techsolutions.com",
    origem: "TELEFONE",
    status: "QUALIFICADO",
    potencial: "ALTO",
    observacoes: "Precisa de regularização urgente - AVCB vencido há 2 meses",
    criadoPor: "Carlos Silva",
    criadoEm: "2025-11-10",
  },
  {
    id: 4,
    nome: "Shopping Praça Central",
    contato: "Ana Paula Costa",
    telefone: "(11) 96666-5555",
    email: "ana.costa@pracacentral.com.br",
    origem: "EMAIL",
    status: "QUALIFICADO",
    potencial: "ALTO",
    observacoes: "Projeto de PPCI para shopping de 60.000m² - orçamento solicitado",
    criadoPor: "Carlos Silva",
    criadoEm: "2025-11-13",
  },
  {
    id: 5,
    nome: "Hospital Vida Nova",
    contato: "Dr. Fernando Ribeiro",
    telefone: "(19) 95555-4444",
    email: "fernando@hospitalvidanova.com.br",
    origem: "INDICACAO",
    status: "EM_CONTATO",
    potencial: "ALTO",
    observacoes: "Adequação de sistemas de prevenção - 3 blocos hospitalares",
    criadoPor: "Carlos Silva",
    criadoEm: "2025-11-14",
  },
  {
    id: 6,
    nome: "Universidade Particular Excellence",
    contato: "Prof. Marcelo Andrade",
    telefone: "(11) 94444-3333",
    email: "infraestrutura@uniexcellence.edu.br",
    origem: "SITE",
    status: "NOVO",
    potencial: "MEDIO",
    observacoes: "Interesse em regularização de 4 campi universitários",
    criadoPor: "Carlos Silva",
    criadoEm: "2025-11-16",
  },
  {
    id: 7,
    nome: "Rede de Hotéis Premium",
    contato: "Carla Mendes",
    telefone: "(21) 93333-2222",
    email: "carla.mendes@redepremium.com.br",
    origem: "REDES_SOCIAIS",
    status: "EM_CONTATO",
    potencial: "ALTO",
    observacoes: "5 hotéis precisam de SPDA e PPCI - contrato em análise",
    criadoPor: "Carlos Silva",
    criadoEm: "2025-11-11",
  },
  {
    id: 8,
    nome: "Grupo Alimentício Brasil",
    contato: "Ricardo Sousa",
    telefone: "(11) 92222-1111",
    email: "ricardo.sousa@grupoalimenticio.com.br",
    origem: "INDICACAO",
    status: "QUALIFICADO",
    potencial: "ALTO",
    observacoes: "Rede com 12 unidades industriais - projeto de regularização completa",
    criadoPor: "Carlos Silva",
    criadoEm: "2025-11-09",
  },
  {
    id: 9,
    nome: "Condomínio Residencial Vista Verde",
    contato: "Síndico José Carlos",
    telefone: "(11) 91111-0000",
    email: "sindico@vistaverde.com.br",
    origem: "TELEFONE",
    status: "NAO_QUALIFICADO",
    potencial: "BAIXO",
    observacoes: "Orçamento muito acima do previsto pelo condomínio",
    criadoPor: "Carlos Silva",
    criadoEm: "2025-11-08",
  },
  {
    id: 10,
    nome: "Academia Corpo em Forma",
    contato: "Patricia Lima",
    telefone: "(11) 90000-9999",
    email: "patricia@corpoemforma.com.br",
    origem: "SITE",
    status: "EM_CONTATO",
    potencial: "MEDIO",
    observacoes: "Rede com 3 unidades - regularização de instalações esportivas",
    criadoPor: "Carlos Silva",
    criadoEm: "2025-11-15",
  },
  {
    id: 11,
    nome: "Clínica Médica Integral",
    contato: "Dr. Gustavo Pereira",
    telefone: "(11) 99888-7777",
    email: "gustavo@clinicaintegral.com.br",
    origem: "EMAIL",
    status: "NOVO",
    potencial: "MEDIO",
    observacoes: "Clínica em expansão - 2 novos andares a regularizar",
    criadoPor: "Carlos Silva",
    criadoEm: "2025-11-17",
  },
  {
    id: 12,
    nome: "Laboratório Farmacêutico Nacional",
    contato: "Eng. Amanda Rodrigues",
    telefone: "(19) 98777-6666",
    email: "amanda@labfarmaceutico.com.br",
    origem: "INDICACAO",
    status: "QUALIFICADO",
    potencial: "ALTO",
    observacoes: "Complexo industrial - precisa de vistoria completa urgente",
    criadoPor: "Carlos Silva",
    criadoEm: "2025-11-10",
  },
  {
    id: 13,
    nome: "Escritório Contábil Master",
    contato: "Daniela Fernandes",
    telefone: "(11) 97666-5555",
    email: "daniela@contabilmaster.com.br",
    origem: "SITE",
    status: "EM_CONTATO",
    potencial: "BAIXO",
    observacoes: "Escritório pequeno - apenas documentação básica",
    criadoPor: "Carlos Silva",
    criadoEm: "2025-11-14",
  },
  {
    id: 14,
    nome: "Supermercado Atacarejo Plus",
    contato: "Marcos Vinícius",
    telefone: "(11) 96555-4444",
    email: "marcos@atacarejopluscom.br",
    origem: "TELEFONE",
    status: "QUALIFICADO",
    potencial: "MEDIO",
    observacoes: "5 lojas a regularizar - análise de proposta em andamento",
    criadoPor: "Carlos Silva",
    criadoEm: "2025-11-12",
  },
  {
    id: 15,
    nome: "Indústria Metalúrgica Forte",
    contato: "Eng. Paulo Henrique",
    telefone: "(11) 95444-3333",
    email: "paulo@metalurgicaforte.com.br",
    origem: "INDICACAO",
    status: "CONVERTIDO",
    potencial: "ALTO",
    observacoes: "Lead convertido em OS-007-2025 - contrato assinado",
    criadoPor: "Carlos Silva",
    criadoEm: "2025-11-05",
  },
  {
    id: 16,
    nome: "Colégio Particular Futuro",
    contato: "Diretora Juliana Campos",
    telefone: "(11) 94333-2222",
    email: "juliana@colegiofuturo.edu.br",
    origem: "REDES_SOCIAIS",
    status: "EM_CONTATO",
    potencial: "MEDIO",
    observacoes: "3 unidades escolares - aguardando aprovação de orçamento",
    criadoPor: "Carlos Silva",
    criadoEm: "2025-11-13",
  },
  {
    id: 17,
    nome: "Posto de Gasolina Rodoviário",
    contato: "Gerente Fábio Santos",
    telefone: "(11) 93222-1111",
    email: "fabio@postorodoviario.com.br",
    origem: "EMAIL",
    status: "NOVO",
    potencial: "BAIXO",
    observacoes: "Primeiro contato - aguardando retorno com documentação",
    criadoPor: "Carlos Silva",
    criadoEm: "2025-11-16",
  },
  {
    id: 18,
    nome: "Farmácia Rede Saúde Total",
    contato: "Proprietário André Costa",
    telefone: "(11) 92111-0000",
    email: "andre@saudetotal.com.br",
    origem: "SITE",
    status: "NAO_QUALIFICADO",
    potencial: "BAIXO",
    observacoes: "Fora da área de atendimento da empresa",
    criadoPor: "Carlos Silva",
    criadoEm: "2025-11-11",
  },
  {
    id: 19,
    nome: "Restaurante e Buffet Premium",
    contato: "Chef Rodrigo Tavares",
    telefone: "(11) 91000-9999",
    email: "rodrigo@buffetpremium.com.br",
    origem: "INDICACAO",
    status: "QUALIFICADO",
    potencial: "MEDIO",
    observacoes: "Espaço de eventos - regularização para ampliação de 500m²",
    criadoPor: "Carlos Silva",
    criadoEm: "2025-11-14",
  },
  {
    id: 20,
    nome: "Empresa de Logística TransCargo",
    contato: "Gerente Operacional Bruno Silva",
    telefone: "(11) 99999-8888",
    email: "bruno@transcargo.com.br",
    origem: "TELEFONE",
    status: "EM_CONTATO",
    potencial: "ALTO",
    observacoes: "3 CDs (centros de distribuição) - projeto de grande porte em análise",
    criadoPor: "Carlos Silva",
    criadoEm: "2025-11-15",
  },
];
